version: '3'

services:
  db:
    build: ./docker_file
    container_name: ipt_localdb
    environment:
      MYSQL_DATABASE: 'ipt_local'
      MYSQL_USER: 'ipt_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    expose:
      - '3306'


